version: '3.9'
services:
  # Node Server
  server:
    build: .
    container_name: 'my-server'
    working_dir: /usr/server
    restart: always
    environment:
      NODE_ENV: 'production'
      DB_HOST: 'my-db'
      REDIS_HOST: 'my-session'
      RABBITMQ_HOST: 'my-queue'
    command: pm2-runtime /usr/server/index.js
    ports:
      - '3000:3000'
    volumes:
      - ./server:/usr/server:ro

  # MySQL Database
  db:
    image: mysql:latest
    container_name: 'my-db'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
      MYSQL_DATABASE: '${DB_NAME}'
    ports:
      - '3001:3306'
    volumes:
      - ./db/data:/var/lib/mysql

  # Redis Session
  session:
    image: redis:latest
    container_name: 'my-session'
    restart: always
    ports:
      - '3002:6379'
    command: redis-server --requirepass "${REDIS_PASS}"
    volumes:
      - ./session/data:/data

  # RabbitMQ Queue
  rabbitmq:
    image: rabbitmq:latest
    container_name: 'my-queue'
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_USER}'
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASS}'
    ports:
      - '3003:5672'
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
