version: '3.9'
services:
  server:
    build:
      context: ../images
      dockerfile: ./Dockerfile-node-lts-alpine
    container_name: ${!DOMAIN}-app
    restart: always
    ports:
      - '${!PUBLIC}${!PORT}:${!PORT}'
    volumes:
      - /var/containers/domains/${!DOMAIN}:/usr/app
    command: pm2-runtime /usr/app/pm2.json
